import fs from 'node:fs';
const file='index.html';
let html=fs.readFileSync(file,'utf8');
if(!html.includes('data-companion-ui="v2"')){
const css=`<style data-companion-ui="v2">.companion-manager{margin-top:6px;padding:14px;border:1px solid #eadfc9;border-radius:16px;background:rgba(255,250,240,.72)}.companion-manager-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.companion-manager-title{font:700 .68rem Montserrat,Arial,sans-serif;letter-spacing:.08em;color:#315889}.companion-manager-help{display:block;font:400 .58rem/1.4 Montserrat,Arial,sans-serif;letter-spacing:0;color:#718095;margin-top:3px}.companion-add{border:0;border-radius:999px;padding:9px 12px;background:#315889;color:#fff;font:700 .58rem Montserrat,Arial,sans-serif;letter-spacing:.04em;cursor:pointer;white-space:nowrap}.companion-list{display:grid;gap:8px}.companion-item{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:6px;align-items:center}.companion-item input{width:100%;margin:0!important}.companion-kind{display:flex;gap:4px}.companion-kind button{border:1px solid #d9e3ec;border-radius:10px;background:#fff;color:#315889;padding:9px 8px;font:600 .56rem Montserrat,Arial,sans-serif;cursor:pointer}.companion-kind button.active{background:#eaf5fc;border-color:#9fc2dd}.companion-remove{width:34px;height:34px;border:0;border-radius:50%;background:#f7e6df;color:#ef7950;font-size:18px;cursor:pointer}.companion-total{text-align:right;margin-top:9px;font:600 .6rem Montserrat,Arial,sans-serif;color:#718095}.party-time-card{max-width:560px;margin:24px auto 8px;padding:18px 20px;text-align:center;border:1px solid rgba(239,121,80,.24);border-radius:20px;background:linear-gradient(135deg,#fff8ef,#fff);box-shadow:0 10px 28px rgba(49,88,137,.08)}.party-time-card .time-kicker{display:block;color:#ef7950;font:800 .58rem Montserrat,Arial,sans-serif;letter-spacing:.18em;text-transform:uppercase}.party-time-card .time-value{display:block;margin-top:5px;color:#315889;font:800 clamp(1.65rem,6vw,2.4rem) Montserrat,Arial,sans-serif}.party-time-card .time-note{display:block;margin-top:4px;color:#718095;font:500 .7rem/1.5 Montserrat,Arial,sans-serif}@media(max-width:600px){.companion-manager-head{align-items:flex-start;flex-direction:column}.companion-add{width:100%}.companion-item{grid-template-columns:minmax(0,1fr) auto}.companion-kind{grid-column:1}.companion-remove{grid-column:2;grid-row:1/3;align-self:center}}</style>`;
const js=`<script data-companion-ui="v2">(()=>{const f=document.getElementById('rsvpForm');if(!f)return;const n=f.querySelector('textarea[name="acompanantes"]'),m=f.querySelector('input[name="menores_18"]');if(!n||!m)return;const nl=n.closest('label'),ml=m.closest('label');if(nl)nl.style.display='none';if(ml)ml.style.display='none';const b=document.createElement('div');b.className='companion-manager';b.innerHTML='<div class="companion-manager-head"><div><div class="companion-manager-title">ACOMPAÑANTES</div><span class="companion-manager-help">Agrega a cada persona por separado.</span></div><button type="button" class="companion-add">+ AGREGAR ACOMPAÑANTE</button></div><div class="companion-list"></div><div class="companion-total">0 acompañantes · 0 adultos · 0 menores</div>';nl.before(b);const list=b.querySelector('.companion-list'),add=b.querySelector('.companion-add'),tot=b.querySelector('.companion-total');let p=[];function render(){list.innerHTML='';p.forEach((x,i)=>{const r=document.createElement('div');r.className='companion-item';r.innerHTML='<input type="text" maxlength="120" placeholder="Nombre del acompañante"><div class="companion-kind"><button type="button">Adulto</button><button type="button">Menor</button></div><button type="button" class="companion-remove" aria-label="Eliminar acompañante">×</button>';const inp=r.querySelector('input'),bs=r.querySelectorAll('.companion-kind button');inp.value=x.nombre;bs[0].classList.toggle('active',!x.es_menor);bs[1].classList.toggle('active',x.es_menor);inp.oninput=()=>{p[i].nombre=inp.value;update()};bs[0].onclick=()=>{p[i].es_menor=false;render()};bs[1].onclick=()=>{p[i].es_menor=true;render()};r.querySelector('.companion-remove').onclick=()=>{p.splice(i,1);render()};list.appendChild(r)});update()}function update(){const mi=p.filter(x=>x.es_menor).length,ad=p.length-mi;tot.textContent=p.length+' acompañante'+(p.length===1?'':'s')+' · '+ad+' adulto'+(ad===1?'':'s')+' · '+mi+' menor'+(mi===1?'':'es')}add.onclick=()=>{if(p.length<20){p.push({nombre:'',es_menor:false});render();list.lastElementChild?.querySelector('input')?.focus()}};f.addEventListener('submit',()=>{p=p.filter(x=>x.nombre.trim());n.value=JSON.stringify(p);m.value=String(p.filter(x=>x.es_menor).length)},{capture:true});render()})();</script>`;
html=html.replace('</style>',css+'</style>');html=html.replace('</body>',js+'</body>');fs.writeFileSync(file,html,'utf8');
}

const invitationFile='invitation.html';
let invitation=fs.readFileSync(invitationFile,'utf8');
invitation=invitation.replace('XIOMARA Y CARLOS','XIOMARA SANTOS Y CARLOS ZUÑIGA');
invitation=invitation.replace('MARTHA Y FERNANDO','MARTHA ACOSTA Y FERNANDO AGUILAR');
if(!invitation.includes('data-party-time="v1"')){
  const partyCss='<style data-party-time="v1">.party-time-card{max-width:560px;margin:24px auto 8px;padding:18px 20px;text-align:center;border:1px solid rgba(239,121,80,.24);border-radius:20px;background:linear-gradient(135deg,#fff8ef,#fff);box-shadow:0 10px 28px rgba(49,88,137,.08)}.party-time-card .time-kicker{display:block;color:#ef7950;font:800 .58rem Montserrat,Arial,sans-serif;letter-spacing:.18em;text-transform:uppercase}.party-time-card .time-value{display:block;margin-top:5px;color:#315889;font:800 clamp(1.65rem,6vw,2.4rem) Montserrat,Arial,sans-serif}.party-time-card .time-note{display:block;margin-top:4px;color:#718095;font:500 .7rem/1.5 Montserrat,Arial,sans-serif}@media(max-width:600px){.party-time-card{margin-left:8px;margin-right:8px}}</style>';
  invitation=invitation.replace('</style>',partyCss+'</style>');
  invitation=invitation.replace('<p class="party-copy">La celebración continúa. Acompáñanos a festejar el cumpleaños de Máximo con mucha alegría.</p>','<p class="party-copy">La celebración continúa. Acompáñanos a festejar el cumpleaños de Máximo con mucha alegría.</p><div class="party-time-card" data-party-time="v1"><span class="time-kicker">FIESTA</span><span class="time-value">A PARTIR DE LAS 2:00 P.M.</span><span class="time-note">Te esperamos para comenzar el festejo.</span></div>');
}
fs.writeFileSync(invitationFile,invitation,'utf8');
